'use client'

import React, { useRef, useState } from 'react'
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table' // Assuming standard UI components
import { Button } from '@/components/ui/button'
import { motion } from 'framer-motion'
import jsPDF from 'jspdf'
import { Download, Loader2, Zap } from 'lucide-react' 
import { SessionParams } from '../medical-voice/[sessionId]/page' 

type Props = {
  history: SessionParams[]
}

function MedicalReport({ history }: Props) {
  const [search, setSearch] = useState('')
  const [currentPage, setCurrentPage] = useState(1)
  const [isDownloading, setIsDownloading] = useState<string | null>(null); // State for loading status
  const itemsPerPage = 5

  // --- Filtering and Pagination Logic ---
  const filteredHistory = history.filter((report) =>
    report.selectedDoctor?.name.toLowerCase().includes(search.toLowerCase()) ||
    report.note?.toLowerCase().includes(search.toLowerCase())
  )

  const totalPages = Math.ceil(filteredHistory.length / itemsPerPage)
  const currentItems = filteredHistory.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  )
  
  // --- Helper to style severity ---
  const getSeverityStyle = (severity: string | undefined) => {
    switch (severity?.toLowerCase()) {
      case 'severe': return 'bg-red-700/80 text-white';
      case 'moderate': return 'bg-orange-500/80 text-white';
      case 'mild': return 'bg-green-600/80 text-white';
      default: return 'bg-gray-600/50 text-gray-400';
    }
  }

  // --- PDF Generation Logic ---
  const handleDownload = (report: SessionParams) => {
    // Prevent multiple downloads
    if (isDownloading) return; 
    setIsDownloading(report.id as string);

    try {
      const doc = new jsPDF()
      let y = 10
      const pageWidth = 190;
      const margin = 10;
      let lineSpacing = 8;
      
      const reportData = report.report;
      
      // 1. Title and Header
      doc.setFontSize(18)
      doc.setFont('helvetica', 'bold');
      doc.text('N-ATLAS AI Consultation Report', margin, y)
      y += 10
      
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal');
      doc.text(`Assistant: ${report.selectedDoctor?.name || 'N/A'} (${report.selectedDoctor?.specialty || 'N/A'})`, margin, y)
      y += 5
      doc.text(`Patient: ${reportData?.user || 'N/A'}`, margin, y)
      y += 5
      doc.text(`Date: ${new Date(report.createdOn).toLocaleString()}`, margin, y)
      y += lineSpacing
      
      // 2. Main Summary and Complaint (use bold font for section titles)
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold');
      doc.text('I. Summary & Complaint', margin, y)
      y += 5
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10)
      
      const mainComplaint = `Main Complaint: ${report.note || 'N/A'}`;
      doc.text(mainComplaint, margin, y);
      y += 6;
      
      const summaryText = reportData?.summary || 'No summary generated by the AI.';
      const summaryLines = doc.splitTextToSize(`Summary: ${summaryText}`, pageWidth);
      doc.text(summaryLines, margin, y);
      y += summaryLines.length * 5; 
      y += lineSpacing;

      // 3. Structured Data
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold');
      doc.text('II. Key Findings', margin, y)
      y += 5
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10)

      doc.text(`Severity: ${reportData?.severity || 'N/A'}`, margin, y); y += 5;
      doc.text(`Duration: ${reportData?.duration || 'N/A'}`, margin, y); y += 5;
      doc.text(`Symptoms: ${reportData?.symptoms?.join(', ') || 'N/A'}`, margin, y); y += 5;
      doc.text(`Medications Mentioned: ${reportData?.medicationsMentioned?.join(', ') || 'None'}`, margin, y); y += lineSpacing;
      
      // 4. Recommendations
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold');
      doc.text('III. Recommendations', margin, y)
      y += 5
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10)
      
      const recommendationsText = reportData?.recommendations?.join('; ') || 'No specific recommendations provided.';
      const recommendationsLines = doc.splitTextToSize(recommendationsText, pageWidth);
      doc.text(recommendationsLines, margin, y);
      y += recommendationsLines.length * 5; 
      
      // Final Save
      doc.save(`medical_report_${report.id || Date.now()}.pdf`)
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF report.');
    } finally {
      setIsDownloading(null);
    }
  }
  
  // NOTE: Exporting the entire table with html2canvas is removed as it's unreliable.
  // The 'Export to PDF' button is removed from the UI.
  // If you need the button, change its onClick handler to alert the user to use the row download.

  return (
    <motion.div
      className="min-h-screen bg-gray-900 text-white p-6 flex flex-col items-center"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
    >
      <motion.h2
        className="text-4xl font-extrabold mb-8 text-center bg-gradient-to-br from-cyan-400 to-purple-400 bg-clip-text text-transparent"
        initial={{ y: -30, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        N-ATLAS Report History Portal
      </motion.h2>

      <motion.div
        className="w-full max-w-6xl bg-gray-800 rounded-2xl shadow-2xl p-6 border border-gray-700"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
          <input
            type="text"
            placeholder="Search assistant or complaint..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value)
              setCurrentPage(1)
            }}
            className="px-4 py-2 rounded-xl bg-gray-700 text-white border border-cyan-400/30 w-full md:w-1/2 focus:ring-purple-500 focus:border-purple-500 transition"
          />
          {/* Export button removed due to unreliability, focus shifted to row download */}
        </div>

        <div className="overflow-x-auto rounded-xl border border-gray-700">
          <Table className="min-w-full text-white">
            <TableCaption className="text-gray-400">
              A list of your recent N-ATLAS medical reports.
            </TableCaption>
            <TableHeader>
              <TableRow className="bg-gray-700/80 border-gray-600">
                <TableHead className="text-white font-semibold">AI Assistant</TableHead>
                <TableHead className="text-white font-semibold">Severity</TableHead>
                <TableHead className="text-white font-semibold">Complaint</TableHead>
                <TableHead className="text-white font-semibold">Date</TableHead>
                <TableHead className="text-white text-right font-semibold">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {currentItems.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-gray-400 py-6">
                    No reports found. Start a consultation to generate a report!
                  </TableCell>
                </TableRow>
              ) : (
                currentItems.map((report, index) => (
                  <motion.tr
                    key={report.id || index}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="hover:bg-gray-700 transition-all border-gray-700/50"
                  >
                    <TableCell className="font-medium text-cyan-300">
                      {report.selectedDoctor?.name || 'N/A'}
                    </TableCell>
                    <TableCell>
                      <span className={`px-3 py-1 rounded-full text-xs font-semibold ${getSeverityStyle(report.report?.severity)}`}>
                        {report.report?.severity?.toUpperCase() || 'N/A'}
                      </span>
                    </TableCell>
                    <TableCell className="max-w-[200px] truncate italic text-gray-300">
                      {report.note || '—'}
                    </TableCell>
                    <TableCell className="text-sm">
                      {new Date(report.createdOn).toLocaleDateString()}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button 
                        size="sm" 
                        onClick={() => handleDownload(report)}
                        disabled={isDownloading === report.id || !report.report} // Disable if no report is present
                        className="bg-purple-600 hover:bg-purple-700 text-white rounded-lg flex items-center gap-2"
                      >
                        {isDownloading === report.id ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <Download className="w-4 h-4" />
                        )}
                        {isDownloading === report.id ? 'Generating...' : 'Download Report'}
                      </Button>
                    </TableCell>
                  </motion.tr>
                ))
              )}
            </TableBody>
          </Table>
        </div>

        {/* Pagination Controls */}
        {totalPages > 1 && (
          <div className="flex justify-between items-center mt-6 p-3 bg-gray-700/50 rounded-xl">
            <Button
              variant="outline"
              size="sm"
              disabled={currentPage === 1 || isDownloading !== null}
              onClick={() => setCurrentPage((p) => p - 1)}
              className="bg-gray-600 hover:bg-gray-500 text-white border-gray-500"
            >
              Previous
            </Button>
            <p className="text-white font-medium">
              Page {currentPage} of {totalPages}
            </p>
            <Button
              variant="outline"
              size="sm"
              disabled={currentPage === totalPages || isDownloading !== null}
              onClick={() => setCurrentPage((p) => p + 1)}
              className="bg-gray-600 hover:bg-gray-500 text-white border-gray-500"
            >
              Next
            </Button>
          </div>
        )}
      </motion.div>
    </motion.div>
  )
}

export default MedicalReport